version: "3.3"


services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
# Certbot создает сертификаты в папке /etc/letsencrypt/
      - ./certbot/conf:/etc/letsencrypt:rw
# Certbot будет записывать свои файлы в ./certbot/www/, а nginx будет обслуживать их через порт 80 каждому пользователю, запр>
# Так Certbot может аутентифицировать наш сервер.
      - ./certbot/www:/var/www/certbot:rw
# директива command: нужна если запрос сертификата делать при запуске контейнера 
# command: certonly --webroot -w /var/www/certbot --email s38.alarm@gmail.com -d minio.krsh.life -d krsh.life -d www.krsh.life --agree-tos
# Шаблон: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos

  nginx:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginxproxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/vc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/vc/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/vc/nginx/log:/var/log/nginx/:rw
      - /home/vc/certbot/conf:/etc/letsencrypt:ro
# Certbot будет записывать свои файлы в ./certbot/www/, 
# а nginx будет обслуживать их через порт 80 каждому пользователю, запрашивающему /.wellknow/acme-challenge/.
      - /home/vc/certbot/www:/var/www/certbot:rw
    ports:
      - 80:80
      - 443:443
      # for vault
      - 8200:8200
      # for keycloak
      # - 8443:443
    networks:
      - minio_net

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9090"
    restart: unless-stopped
    volumes:
      - /mnt/nas:/data
    env_file:
      - /home/vc/minio/.env
    ports:
      # - 9090:9090
      - 9000:9000
    expose:
      - "9090"
    #environment:
      #- VIRTUAL_HOST=192.168.106.31
      #- VIRTUAL_PORT=9090
    networks:
      - minio_net
    depends_on:
      - nginx

  

