version: "3.3"

include:
  - ../vc/docker_compose/vault.yaml
  - ../vc/docker_compose/basic_minio.yaml
  # - path: ../docker_compose/vault.yaml
  # - path: ../docker_compose/basic_minio.yaml
  #   project_directory: ..

services:
 
  keycloak:
    image: quay.io/keycloak/keycloak
    command: start-dev
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres_keycloak
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_PASSWORD=1223
      - KC_DB_USERNAME=keycloak
      - KC_DB_SCHEMA=public
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME_ADMIN_URL=https://localhost:8443
      - KC_HOSTNAME_URL=https://localhost:8443
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - minio_net

  postgres_keycloak:
    image: postgres:15.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=1223 
    healthcheck:
      test: "exit 0"
    ports:
      - 5436:5439
    networks:
      - minio_net


volumes:
  pgdata_keycloak:

networks:
  minio_net:

